name: DigioChallenge
options:
  bundleIdPrefix: com.weslleyquadros
  deploymentTarget:
    iOS: '12.0'

targets:
  DigioChallenge:
    type: application
    platform: iOS
    sources:
      - path: Sources/DigioChallenge
    resources:
      - path: Resources
    info:
        path: Info.plist
        properties:
          UIAppFonts:
            - proximanova_regular.ttf
            - proximanova_black.otf
            - proximanova_bold.otf
            - proximanova_light.otf
          UILaunchStoryboardName: LaunchScreen
          UISupportedInterfaceOrientations:
            - UIInterfaceOrientationPortrait
          UIUserInterfaceStyle: "Light"
    settings:
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    preBuildScripts:
      - name: SwiftLint
        script: |
          # Adds support for Apple Silicon brew directory
            export PATH="$PATH:/opt/homebrew/bin"

            if which swiftlint >/dev/null; then
                swiftlint
            else
                echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
            fi

    scheme:
      testTargets:
        - DigioChallengeTests
      gatherCoverageData: true
      coverageTargets:
        - DigioChallenge

  DigioChallengeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/DigioChallengeTests
    info:
        path: Tests/Info.plist
    dependencies:
      - target: DigioChallenge
